CREATE TABLE users (
  dtype VARCHAR(31) NOT NULL,
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  cpf VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','CLIENT') NOT NULL,
  address VARCHAR(255),
  birth_date DATETIME(6)
);

CREATE TABLE vehicles (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  brand VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  color VARCHAR(255),
  license_plate VARCHAR(255) UNIQUE,
  name VARCHAR(255) NOT NULL,
  p_year INT NOT NULL,
  owner_id VARCHAR(255),
  CONSTRAINT FK_owner_id FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL
);

